# Generated by Django 4.1.3 on 2022-12-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='')),
                ('password', models.CharField(max_length=50, verbose_name='')),
                ('role', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
    ]
