# Generated by Django 4.1.3 on 2022-12-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.AddField(
            model_name='account',
            name='pwd',
            field=models.CharField(default=0, max_length=50, verbose_name='Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='u_name',
            field=models.CharField(default=0, max_length=50, verbose_name='User Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(max_length=50, verbose_name='User Role'),
        ),
    ]
