# Generated by Django 4.1.3 on 2022-12-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50, verbose_name='')),
                ('l_name', models.CharField(max_length=50, verbose_name='')),
                ('mobile_no', models.IntegerField(verbose_name='')),
                ('email_add', models.EmailField(max_length=254, verbose_name='')),
                ('edu_qual', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
    ]
